### ISSUE TITLE
Unable to compile project when enable strict checking of objc_msgSend calls flag is enabled

### ISSUE THREAD

**Issue by drekka** [tomersh/AppleGuice#12]
Hi, am trying to use AppleGuice in an ARC project. I have it as a git submodule and have added a sub project in Xcode. But I'm having a number of issues trying to compile it. At the moment it's complaining that "Too many arguments for function all, expecting 0, have 2" in this code:

    static id _appleGuiceInjectionInitWrapper(id self, SEL _cmd) {
        ...
        returnValue = _originalInitMethodImp(self, _cmd);

I fixed it but it started complaining about other code. 

Can you give any advice? 

P.S> no I don't use Cocoapods. I don't like the way they work.

**Comment by tomersh** [comment]
Hey,
Cocapods adds `-lc++` to other Linker Flags. Without Cocoapods, you will need to add it manually.

**Comment by drekka** [comment]
Thanks. That helped later, but didn't solve the error I was getting. I did some digging and found a fix. Wherever there is a msg_send I added a cast to satisfy the compiler. So:

    returnValue = _originalInitMethodImp(self, _cmd);

Becomes:

    returnValue = ((id (*)(id, SEL)) _originalInitMethodImp)(self, _cmd);

I had to update the retain and release macros, add the -lc++ flag you suggested and now everything compiles.

**Comment by tomersh** [comment]
Would you like to create  a pull request with that fix?

**Comment by itsthejb** [comment]
Seems like a quick fix...?
