### ISSUE TITLE
Initializer Injection

### ISSUE THREAD

**Issue by vinayganesh** [tomersh/AppleGuice#14]
What about initializer injection ? How would you go by and inform AppleGuice to use a designated constructor rather than just Init ?

**Comment by tomersh** [comment]
Applguice currently does not to support initializers other than simple `init` (for injectable services). We did it for the simplicity of the framework and its usage. In other DI frameworks, you need to declare your designated initializer and how to bind its variables. AppleGuice simply calls init, which keeps your code cleaner and makes it more robust.
Having said that, constructors where all of its variables are injectable services can (and will be) supported.
Currently, you can convert the following:
```
//.h
-(instancetype) initWithInjectable1:(id<MyInjService1>) inj1 andInjectable2:(id<MyInjService2>) inj2;
```

to:
```
//.h
@property (nonatomic, strong, readonly) id<MyInjService1> ioc_inj1;
@property (nonatomic, strong, readonly) id<MyInjService1> ioc_inj2;

-(instancetype) init;
```
